/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class NativeLib */

#ifndef _Included_NativeLib
#define _Included_NativeLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     NativeLib
 * Method:    memoryEater
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_NativeLib_memoryEater
  (JNIEnv *, jobject);

/*
 * Class:     NativeLib
 * Method:    allocateOneKB
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_NativeLib_allocateOneKB
  (JNIEnv *, jobject);

/*
 * Class:     NativeLib
 * Method:    crashWithStackTrace
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_NativeLib_crashWithStackTrace
  (JNIEnv *, jobject);

/*
 * Class:     NativeLib
 * Method:    getStringLength
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_NativeLib_getStringLength
  (JNIEnv *, jobject, jstring);

/*
 * Class:     NativeLib
 * Method:    callObjectMethod
 * Signature: (LTestClass;)V
 */
JNIEXPORT void JNICALL Java_NativeLib_callObjectMethod
  (JNIEnv *, jobject, jobject);

/*
 * Class:     NativeLib
 * Method:    changeObjectField
 * Signature: (LTestClass;I)V
 */
JNIEXPORT void JNICALL Java_NativeLib_changeObjectField
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     NativeLib
 * Method:    allocateStructure
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_NativeLib_allocateStructure
  (JNIEnv *, jobject);

/*
 * Class:     NativeLib
 * Method:    getStructureField
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_NativeLib_getStructureField
  (JNIEnv *, jobject, jlong);

/*
 * Class:     NativeLib
 * Method:    freeMemory
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_NativeLib_freeMemory
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
